services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./config/jellyfin:/config
      - ./media/shows:/data/tvshows
      - ./media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/radarr:/config
      - ./media/movies:/movies #optional
      - ./downloads/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/sonarr:/config
      - ./media/shows:/tv #optional
      - ./downloads/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # - NZBGET_USER=nzbget #optional
      # - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - ./config/nzbget:/config
      - ./downloads/complete:/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped




